// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhkqgwidgzrtpblgehsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oa3Fnd2lkZ3pydHBibGdlaHNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzcyODMsImV4cCI6MjA2Mzc1MzI4M30.Zi379iPUX_K_Fuh7jTGEP0Vi2ledrOWPBqlbo8MLSMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);